-- Source http://sites.nationalacademies.org/PGA/Resdoc/PGA_044522

INSERT INTO `branches` VALUES (1,'Life Sciences',NULL);
INSERT INTO `branches` VALUES (2,'Biochemistry, Biophysics, and Structural Biology',1);
INSERT INTO `branches` VALUES (3,'Biochemistry',2);
INSERT INTO `branches` VALUES (4,'Biogeochemistry',2);
INSERT INTO `branches` VALUES (5,'Biophysics',2);
INSERT INTO `branches` VALUES (6,'Molecular Biology',2);
INSERT INTO `branches` VALUES (7,'Structural Biology',2);
INSERT INTO `branches` VALUES (8,'Cell and Developmental Biology',1);
INSERT INTO `branches` VALUES (9,'Anatomy',8);
INSERT INTO `branches` VALUES (10,'Cell Biology',8);
INSERT INTO `branches` VALUES (11,'Developmental Biology',8);
INSERT INTO `branches` VALUES (12,'Cancer Biology',8);
INSERT INTO `branches` VALUES (13,'Ecology and Evolutionary Biology',1);
INSERT INTO `branches` VALUES (14,'Behavior and Ethology',13);
INSERT INTO `branches` VALUES (15,'Biogeochemistry',13);
INSERT INTO `branches` VALUES (16,'Botany',13);
INSERT INTO `branches` VALUES (17,'Evolution',13);
INSERT INTO `branches` VALUES (18,'Population Biology',13);
INSERT INTO `branches` VALUES (19,'Terrestrial and Aquatic Ecology',13);
INSERT INTO `branches` VALUES (20,'Public Health',1);
INSERT INTO `branches` VALUES (21,'Environmental Health',20);
INSERT INTO `branches` VALUES (22,'Epidemiology',20);
INSERT INTO `branches` VALUES (23,'Biostatistics',20);
INSERT INTO `branches` VALUES (24,'Genetics and Genomics',1);
INSERT INTO `branches` VALUES (25,'Computational Biology',24);
INSERT INTO `branches` VALUES (26,'Genetics',24);
INSERT INTO `branches` VALUES (27,'Genomics',24);
INSERT INTO `branches` VALUES (28,'Molecular genetics',24);
INSERT INTO `branches` VALUES (29,'Immunology and Infectious Disease',1);
INSERT INTO `branches` VALUES (30,'Immunity',29);
INSERT INTO `branches` VALUES (31,'Immunology of Infectious Disease',29);
INSERT INTO `branches` VALUES (32,'Immunopathology',29);
INSERT INTO `branches` VALUES (33,'Immunoprophylaxis and Therapy',29);
INSERT INTO `branches` VALUES (34,'Pathology',29);
INSERT INTO `branches` VALUES (35,'Parasitology',29);
INSERT INTO `branches` VALUES (36,'Kinesiology',1);
INSERT INTO `branches` VALUES (37,'Biomechanics',36);
INSERT INTO `branches` VALUES (38,'Exercise Physiology',36);
INSERT INTO `branches` VALUES (39,'Motor Control',36);
INSERT INTO `branches` VALUES (40,'Psychology of Movement',36);
INSERT INTO `branches` VALUES (41,'Microbiology',1);
INSERT INTO `branches` VALUES (42,'Bacteriology',41);
INSERT INTO `branches` VALUES (43,'Environmental Microbiology',41);
INSERT INTO `branches` VALUES (44,'Microbial Ecology',41);
INSERT INTO `branches` VALUES (45,'Microbial Physiology',41);
INSERT INTO `branches` VALUES (46,'Pathogenic Microbiology',41);
INSERT INTO `branches` VALUES (47,'Virology',41);
INSERT INTO `branches` VALUES (48,'Neuroscience and Neurobiology',1);
INSERT INTO `branches` VALUES (49,'Behavioral Neurobiology',48);
INSERT INTO `branches` VALUES (50,'Cognitive Neuroscience',48);
INSERT INTO `branches` VALUES (51,'Computational Neuroscience',48);
INSERT INTO `branches` VALUES (52,'Developmental Neuroscience',48);
INSERT INTO `branches` VALUES (53,'Molecular and Cellular Neuroscience',48);
INSERT INTO `branches` VALUES (54,'Systems Neuroscience',48);
INSERT INTO `branches` VALUES (55,'Integrated Biomedical Sciences',1);
INSERT INTO `branches` VALUES (56,'Nursing',1);
INSERT INTO `branches` VALUES (57,'Pharmacology, Toxicology and Environmental Health',1);
INSERT INTO `branches` VALUES (58,'Environmental Health',57);
INSERT INTO `branches` VALUES (59,'Medicinal Chemistry and Pharmaceutics',57);
INSERT INTO `branches` VALUES (60,'Pharmacology',57);
INSERT INTO `branches` VALUES (61,'Toxicology',57);
INSERT INTO `branches` VALUES (62,'Physiology',1);
INSERT INTO `branches` VALUES (63,'Cellular and Molecular Physiology',62);
INSERT INTO `branches` VALUES (64,'Comparative and Evolutionary Physiology',62);
INSERT INTO `branches` VALUES (65,'Endocrinology',62);
INSERT INTO `branches` VALUES (66,'Exercise Physiology',62);
INSERT INTO `branches` VALUES (67,'Systems and Integrative Physiology',62);
INSERT INTO `branches` VALUES (68,'Animal Sciences',1);
INSERT INTO `branches` VALUES (69,'Aquaculture and Fisheries',68);
INSERT INTO `branches` VALUES (70,'Dairy Science',68);
INSERT INTO `branches` VALUES (71,'Poultry / Avian Science',68);
INSERT INTO `branches` VALUES (72,'Zoology',68);
INSERT INTO `branches` VALUES (73,'Entomology',1);
INSERT INTO `branches` VALUES (74,'Food Science',1);
INSERT INTO `branches` VALUES (75,'Food Processing',74);
INSERT INTO `branches` VALUES (76,'Food Microbiology',74);
INSERT INTO `branches` VALUES (77,'Food Chemistry',74);
INSERT INTO `branches` VALUES (78,'Food Biotechnology',74);
INSERT INTO `branches` VALUES (79,'Forestry and Forest Sciences',1);
INSERT INTO `branches` VALUES (80,'Forest Biology',79);
INSERT INTO `branches` VALUES (81,'Forest Management',79);
INSERT INTO `branches` VALUES (82,'Wood Science and Pulp/Paper Technology',79);
INSERT INTO `branches` VALUES (83,'Nutrition',1);
INSERT INTO `branches` VALUES (84,'Comparative Nutrition',83);
INSERT INTO `branches` VALUES (85,'Human and Clinical Nutrition',83);
INSERT INTO `branches` VALUES (86,'International and Community Nutrition',83);
INSERT INTO `branches` VALUES (87,'Molecular, Genetic, and Biochemical Nutrition',83);
INSERT INTO `branches` VALUES (88,'Nutritional Epidemiology',83);
INSERT INTO `branches` VALUES (89,'Plant Sciences',1);
INSERT INTO `branches` VALUES (90,'Agronomy and Crop Sciences',89);
INSERT INTO `branches` VALUES (91,'Botany',89);
INSERT INTO `branches` VALUES (92,'Horticulture',89);
INSERT INTO `branches` VALUES (93,'Plant Biology',89);
INSERT INTO `branches` VALUES (94,'Plant Pathology',89);
INSERT INTO `branches` VALUES (95,'Plant Breeding and Genetics',89);
INSERT INTO `branches` VALUES (96,'Bioinformatics',1);
INSERT INTO `branches` VALUES (97,'Biotechnology',1);
INSERT INTO `branches` VALUES (98,'Systems Biology',1);
INSERT INTO `branches` VALUES (99,'Physical Sciences',NULL);
INSERT INTO `branches` VALUES (100,'Astrophysics and Astronomy',99);
INSERT INTO `branches` VALUES (101,'Physical Processes',100);
INSERT INTO `branches` VALUES (102,'Instrumentation',100);
INSERT INTO `branches` VALUES (103,'The Sun and the Solar System',100);
INSERT INTO `branches` VALUES (104,'Stars, Interstellar Medium and the Galaxy',100);
INSERT INTO `branches` VALUES (105,'External Galaxies',100);
INSERT INTO `branches` VALUES (106,'Cosmology',100);
INSERT INTO `branches` VALUES (107,'Chemistry',99);
INSERT INTO `branches` VALUES (108,'Analytical Chemistry',107);
INSERT INTO `branches` VALUES (109,'Biochemistry',107);
INSERT INTO `branches` VALUES (110,'Environmental Chemistry',107);
INSERT INTO `branches` VALUES (111,'Materials Chemistry',107);
INSERT INTO `branches` VALUES (112,'Medicinal-Pharmaceutical Chemistry',107);
INSERT INTO `branches` VALUES (113,'Inorganic Chemistry',107);
INSERT INTO `branches` VALUES (114,'Organic Chemistry',107);
INSERT INTO `branches` VALUES (115,'Physical Chemistry',107);
INSERT INTO `branches` VALUES (116,'Polymer Chemistry',107);
INSERT INTO `branches` VALUES (117,'Earth Sciences',99);
INSERT INTO `branches` VALUES (118,'Biogeochemistry',117);
INSERT INTO `branches` VALUES (119,'Cosmochemistry',117);
INSERT INTO `branches` VALUES (120,'Environmental Sciences',117);
INSERT INTO `branches` VALUES (121,'Geology',117);
INSERT INTO `branches` VALUES (122,'Geochemistry',117);
INSERT INTO `branches` VALUES (123,'Geophysics and Seismology',117);
INSERT INTO `branches` VALUES (124,'Glaciology',117);
INSERT INTO `branches` VALUES (125,'Mineral Physics',117);
INSERT INTO `branches` VALUES (126,'Paleobiology',117);
INSERT INTO `branches` VALUES (127,'Paleontology',117);
INSERT INTO `branches` VALUES (128,'Soil Science',117);
INSERT INTO `branches` VALUES (129,'Tectonics and Structure',117);
INSERT INTO `branches` VALUES (130,'Vulcanology',117);
INSERT INTO `branches` VALUES (131,'Oceanography, Atmospheric Sciences and Meteorology',99);
INSERT INTO `branches` VALUES (132,'Atmospheric Sciences',131);
INSERT INTO `branches` VALUES (133,'Climate',131);
INSERT INTO `branches` VALUES (134,'Fresh Water Studies',131);
INSERT INTO `branches` VALUES (135,'Meteorology',131);
INSERT INTO `branches` VALUES (136,'Oceanography',131);
INSERT INTO `branches` VALUES (137,'Physics',99);
INSERT INTO `branches` VALUES (138,'Atomic, Molecular and Optical Physics',137);
INSERT INTO `branches` VALUES (139,'Biological and Chemical Physics',137);
INSERT INTO `branches` VALUES (140,'Condensed Matter Physics',137);
INSERT INTO `branches` VALUES (141,'Relativity and Gravity',137);
INSERT INTO `branches` VALUES (142,'Elementary Particles, Fields and String Theory',137);
INSERT INTO `branches` VALUES (143,'Engineering Physics',137);
INSERT INTO `branches` VALUES (144,'Fluid Dynamics',137);
INSERT INTO `branches` VALUES (145,'Non-linear Dynamics',137);
INSERT INTO `branches` VALUES (146,'Nuclear',137);
INSERT INTO `branches` VALUES (147,'Optics',137);
INSERT INTO `branches` VALUES (148,'Plasma and Beam Physics',137);
INSERT INTO `branches` VALUES (149,'Quantum Physics',137);
INSERT INTO `branches` VALUES (150,'Mathematical Sciences',NULL);
INSERT INTO `branches` VALUES (151,'Applied Mathematics',150);
INSERT INTO `branches` VALUES (152,'Control Theory',151);
INSERT INTO `branches` VALUES (153,'Dynamic Systems',151);
INSERT INTO `branches` VALUES (154,'Numerical Analysis and Computation',151);
INSERT INTO `branches` VALUES (155,'Partial Differential Equations',151);
INSERT INTO `branches` VALUES (156,'Ordinary Differential Equations and Applied Dynamics',151);
INSERT INTO `branches` VALUES (157,'Mathematics',150);
INSERT INTO `branches` VALUES (158,'Algebra',157);
INSERT INTO `branches` VALUES (159,'Algebraic Geometry',157);
INSERT INTO `branches` VALUES (160,'Mathematical Analysis',157);
INSERT INTO `branches` VALUES (161,'Discrete Mathematics and Combinatorics',157);
INSERT INTO `branches` VALUES (162,'Dynamics/Dynamical Systems',157);
INSERT INTO `branches` VALUES (163,'Geometry and Topology',157);
INSERT INTO `branches` VALUES (164,'Harmonic Analysis and Representation',157);
INSERT INTO `branches` VALUES (165,'Logic and Foundations',157);
INSERT INTO `branches` VALUES (166,'Number Theory',157);
INSERT INTO `branches` VALUES (167,'Set Theory',157);
INSERT INTO `branches` VALUES (168,'Statistics and Probability',150);
INSERT INTO `branches` VALUES (169,'Applied Statistics',168);
INSERT INTO `branches` VALUES (170,'Biostatistics',168);
INSERT INTO `branches` VALUES (171,'Biometry',168);
INSERT INTO `branches` VALUES (172,'Probability',168);
INSERT INTO `branches` VALUES (173,'Statistical Methodology',168);
INSERT INTO `branches` VALUES (174,'Statistical Theory',168);
INSERT INTO `branches` VALUES (175,'Computer Science',NULL);
INSERT INTO `branches` VALUES (176,'Artificial Intelligence',175);
INSERT INTO `branches` VALUES (177,'Computation and Language',175);
INSERT INTO `branches` VALUES (178,'Computational Complexity',175);
INSERT INTO `branches` VALUES (179,'Computational Engineering, Finance, and Science',175);
INSERT INTO `branches` VALUES (180,'Computational Geometry',175);
INSERT INTO `branches` VALUES (181,'Computer Science and Game Theory',175);
INSERT INTO `branches` VALUES (182,'Computer Vision and Pattern Recognition',175);
INSERT INTO `branches` VALUES (183,'Computers and Society',175);
INSERT INTO `branches` VALUES (184,'Data Structures and Algorithms',175);
INSERT INTO `branches` VALUES (185,'Databases',175);
INSERT INTO `branches` VALUES (186,'Digital Libraries',175);
INSERT INTO `branches` VALUES (187,'Distributed, Parallel, and Cluster Computing',175);
INSERT INTO `branches` VALUES (188,'Emerging Technologies',175);
INSERT INTO `branches` VALUES (189,'Formal Languages and Automata Theory',175);
INSERT INTO `branches` VALUES (190,'Computer Graphics',175);
INSERT INTO `branches` VALUES (191,'Hardware Architecture',175);
INSERT INTO `branches` VALUES (192,'Human-Computer Interaction',175);
INSERT INTO `branches` VALUES (193,'Information Retrieval',175);
INSERT INTO `branches` VALUES (194,'Information Theory',175);
INSERT INTO `branches` VALUES (195,'Machine Learning',175);
INSERT INTO `branches` VALUES (196,'Logic in Computer Science',175);
INSERT INTO `branches` VALUES (197,'Mathematical Software',175);
INSERT INTO `branches` VALUES (198,'Multimedia',175);
INSERT INTO `branches` VALUES (199,'Networking and Internet Architecture',175);
INSERT INTO `branches` VALUES (200,'Neural and Evolutionary Computing',175);
INSERT INTO `branches` VALUES (201,'Numerical Analysis',175);
INSERT INTO `branches` VALUES (202,'Operating Systems',175);
INSERT INTO `branches` VALUES (203,'Programming Languages',175);
INSERT INTO `branches` VALUES (204,'Robotics',175);
INSERT INTO `branches` VALUES (205,'Social and Information Networks',175);
INSERT INTO `branches` VALUES (206,'Computer Sound',175);
INSERT INTO `branches` VALUES (207,'Symbolic Computation',175);
INSERT INTO `branches` VALUES (208,'Computer Systems and Control',175);
INSERT INTO `branches` VALUES (209,'Engineering',NULL);
INSERT INTO `branches` VALUES (210,'Aerospace Engineering',209);
INSERT INTO `branches` VALUES (211,'Space Vehicles',210);
INSERT INTO `branches` VALUES (212,'Systems Engineering and Multidisciplinary Design Optimization',210);
INSERT INTO `branches` VALUES (213,'Aerodynamics and Fluid Mechanics',210);
INSERT INTO `branches` VALUES (214,'Astrodynamics',210);
INSERT INTO `branches` VALUES (215,'Structures and Materials',210);
INSERT INTO `branches` VALUES (216,'Propulsion and Power',210);
INSERT INTO `branches` VALUES (217,'Navigation, Guidance, Control and Dynamics',210);
INSERT INTO `branches` VALUES (218,'Multi-Vehicle Systems and Air Traffic Control',210);
INSERT INTO `branches` VALUES (219,'Biomedical Engineering and Bioengineering',209);
INSERT INTO `branches` VALUES (220,'Biological Engineering',219);
INSERT INTO `branches` VALUES (221,'Bioelectrical and Neuroengineering',219);
INSERT INTO `branches` VALUES (222,'Bioimaging and biomedical optics',219);
INSERT INTO `branches` VALUES (223,'Biomaterials',219);
INSERT INTO `branches` VALUES (224,'Biomechanics and biotransport',219);
INSERT INTO `branches` VALUES (225,'Biomedical devices and instrumentation',219);
INSERT INTO `branches` VALUES (226,'Molecular, cellular, and tissue engineering',219);
INSERT INTO `branches` VALUES (227,'Systems and integrative engineering',219);
INSERT INTO `branches` VALUES (228,'Chemical Engineering',209);
INSERT INTO `branches` VALUES (229,'Biochemical and Biomolecular Engineering',228);
INSERT INTO `branches` VALUES (230,'Catalysis and Reaction Engineering',228);
INSERT INTO `branches` VALUES (231,'Complex Fluids',228);
INSERT INTO `branches` VALUES (232,'Membrane Science',228);
INSERT INTO `branches` VALUES (233,'Petroleum Engineering',228);
INSERT INTO `branches` VALUES (234,'Polymer Science',228);
INSERT INTO `branches` VALUES (235,'Process Control and Systems',228);
INSERT INTO `branches` VALUES (236,'Thermodynamics',228);
INSERT INTO `branches` VALUES (237,'Transport Phenomena',228);
INSERT INTO `branches` VALUES (238,'Civil and Environmental Engineering',209);
INSERT INTO `branches` VALUES (239,'Civil Engineering',238);
INSERT INTO `branches` VALUES (240,'Construction Engineering/management',238);
INSERT INTO `branches` VALUES (241,'Environmental Engineering',238);
INSERT INTO `branches` VALUES (242,'Geotechnical Engineering',238);
INSERT INTO `branches` VALUES (243,'Structural Engineering',238);
INSERT INTO `branches` VALUES (244,'Computer Engineering',209);
INSERT INTO `branches` VALUES (245,'Computer and Systems Architecture',244);
INSERT INTO `branches` VALUES (246,'Digital Circuits',244);
INSERT INTO `branches` VALUES (247,'Data Storage Systems',244);
INSERT INTO `branches` VALUES (248,'Digital Communications and Networking',244);
INSERT INTO `branches` VALUES (249,'Hardware Systems',244);
INSERT INTO `branches` VALUES (250,'High Energy Physics',99);
INSERT INTO `branches` VALUES (251,'Electrical Engineering',209);
INSERT INTO `branches` VALUES (252,'Biomedical Engineering',251);
INSERT INTO `branches` VALUES (253,'Controls and Control Theory',251);
INSERT INTO `branches` VALUES (254,'Electrical and Electronics Engineering',251);
INSERT INTO `branches` VALUES (255,'Electromagnetics and Photonics',251);
INSERT INTO `branches` VALUES (256,'Electronic Devices and Semiconductor Manufacturing',251);
INSERT INTO `branches` VALUES (257,'Nanotechnology Fabrication',251);
INSERT INTO `branches` VALUES (258,'Power and Energy',251);
INSERT INTO `branches` VALUES (259,'Signal Processing',251);
INSERT INTO `branches` VALUES (260,'Systems and Communications Engineering',251);
INSERT INTO `branches` VALUES (261,'VLSI and circuits: Embedded/Hardware Systems',251);
INSERT INTO `branches` VALUES (262,'Materials Science and Engineering',209);
INSERT INTO `branches` VALUES (263,'Biology and Biomimetic Materials',261);
INSERT INTO `branches` VALUES (264,'Ceramic Materials',261);
INSERT INTO `branches` VALUES (265,'Metallurgy',261);
INSERT INTO `branches` VALUES (266,'Polymer and Organic Materials',261);
INSERT INTO `branches` VALUES (267,'Semiconductor and Optical Materials',261);
INSERT INTO `branches` VALUES (268,'Structural Materials',261);
INSERT INTO `branches` VALUES (269,'Mechanical Engineering',209);
INSERT INTO `branches` VALUES (270,'Acoustics, Dynamics, and Controls',269);
INSERT INTO `branches` VALUES (271,'Applied Mechanics',269);
INSERT INTO `branches` VALUES (272,'Biomechanical Engineering',269);
INSERT INTO `branches` VALUES (273,'Computer-Aided Engineering and Design',269);
INSERT INTO `branches` VALUES (274,'Electro-Mechanical Systems',269);
INSERT INTO `branches` VALUES (275,'Energy Systems',269);
INSERT INTO `branches` VALUES (276,'Heat Transfer, Combustion',269);
INSERT INTO `branches` VALUES (277,'Manufacturing',269);
INSERT INTO `branches` VALUES (278,'Ocean Engineering',269);
INSERT INTO `branches` VALUES (279,'Tribology',269);
INSERT INTO `branches` VALUES (280,'Operations Research, Systems Engineering and Industrial Engineering',209);
INSERT INTO `branches` VALUES (281,'Ergonomics',280);
INSERT INTO `branches` VALUES (282,'Industrial Engineering',280);
INSERT INTO `branches` VALUES (283,'Operational Research',280);
INSERT INTO `branches` VALUES (284,'Systems Engineering',280);
INSERT INTO `branches` VALUES (285,'Nanoscience and Nanotechnology',209);
INSERT INTO `branches` VALUES (286,'Nuclear Engineering',209);
INSERT INTO `branches` VALUES (287,'Social and Behavioral Sciences',NULL);
INSERT INTO `branches` VALUES (288,'Agricultural and Resource Economics',287);
INSERT INTO `branches` VALUES (289,'Anthropology',287);
INSERT INTO `branches` VALUES (290,'Archaeological Antropology',289);
INSERT INTO `branches` VALUES (291,'Biological and Physical Anthropology',289);
INSERT INTO `branches` VALUES (292,'Linguistic Anthrolpology',289);
INSERT INTO `branches` VALUES (293,'Social and Cultural Anthropology',289);
INSERT INTO `branches` VALUES (294,'Communication',287);
INSERT INTO `branches` VALUES (295,'Broadcast/Video Studies',294);
INSERT INTO `branches` VALUES (296,'Communication Technology and New Media',294);
INSERT INTO `branches` VALUES (297,'Critical and Cultural Studies',294);
INSERT INTO `branches` VALUES (298,'Gender, Race, Sexuality, and Ethnicity in Communication',294);
INSERT INTO `branches` VALUES (299,'Health Communication',294);
INSERT INTO `branches` VALUES (300,'International and Intercultural Communication',294);
INSERT INTO `branches` VALUES (301,'Interpersonal/Small Group Communication',294);
INSERT INTO `branches` VALUES (302,'Journalism Studies',294);
INSERT INTO `branches` VALUES (303,'Mass Communication',294);
INSERT INTO `branches` VALUES (304,'Organizational Communication',294);
INSERT INTO `branches` VALUES (305,'Public Relations/Advertising',294);
INSERT INTO `branches` VALUES (306,'Social Influence and Political Communication',294);
INSERT INTO `branches` VALUES (307,'Speech and Rhetorical Studies',294);
INSERT INTO `branches` VALUES (308,'Economics',287);
INSERT INTO `branches` VALUES (309,'Behavioral Economics',308);
INSERT INTO `branches` VALUES (310,'Econometrics',308);
INSERT INTO `branches` VALUES (311,'Economic History',308);
INSERT INTO `branches` VALUES (312,'Economic Theory',308);
INSERT INTO `branches` VALUES (313,'Growth and Development',308);
INSERT INTO `branches` VALUES (314,'Industrial Organization',308);
INSERT INTO `branches` VALUES (315,'International Economics',308);
INSERT INTO `branches` VALUES (316,'Labor Economics',308);
INSERT INTO `branches` VALUES (317,'Macroeconomics',308);
INSERT INTO `branches` VALUES (318,'Public Economics',308);
INSERT INTO `branches` VALUES (319,'Geography',287);
INSERT INTO `branches` VALUES (320,'Physical and Environmental Geography',319);
INSERT INTO `branches` VALUES (321,'Human Geography',319);
INSERT INTO `branches` VALUES (322,'Nature and Society Relations',319);
INSERT INTO `branches` VALUES (323,'Geographic Information Sciences',319);
INSERT INTO `branches` VALUES (324,'Linguistics',287);
INSERT INTO `branches` VALUES (325,'Anthropological Linguistics/Sociolinguistics',324);
INSERT INTO `branches` VALUES (326,'Applied Linguistics',324);
INSERT INTO `branches` VALUES (327,'Comparative and Historical Linguistics',324);
INSERT INTO `branches` VALUES (328,'Computational Linguistics',324);
INSERT INTO `branches` VALUES (329,'Discourse/Text Linguistics',324);
INSERT INTO `branches` VALUES (330,'First/Second Language Acquisition',324);
INSERT INTO `branches` VALUES (331,'Typological Linguistics and Linguistic Diversity',324);
INSERT INTO `branches` VALUES (332,'Language Description/Documentation',324);
INSERT INTO `branches` VALUES (333,'Morphology',324);
INSERT INTO `branches` VALUES (334,'Phonetics/Phonology',324);
INSERT INTO `branches` VALUES (335,'Psycholinguistics/Neurolinguistics',324);
INSERT INTO `branches` VALUES (336,'Semantics/Pragmatics',324);
INSERT INTO `branches` VALUES (337,'Syntax',324);
INSERT INTO `branches` VALUES (338,'Political Science',287);
INSERT INTO `branches` VALUES (339,'Comparative Politics',338);
INSERT INTO `branches` VALUES (340,'International Relations',338);
INSERT INTO `branches` VALUES (341,'Models and Methods',338);
INSERT INTO `branches` VALUES (342,'Political Theory',338);
INSERT INTO `branches` VALUES (343,'Public Affairs, Public Policy and Public Administration',287);
INSERT INTO `branches` VALUES (344,'Public Administration',343);
INSERT INTO `branches` VALUES (345,'Public Affairs',343);
INSERT INTO `branches` VALUES (346,'Public Policy',343);
INSERT INTO `branches` VALUES (347,'Urban Studies',343);
INSERT INTO `branches` VALUES (348,'Psychology',287);
INSERT INTO `branches` VALUES (349,'Biological Psychology',348);
INSERT INTO `branches` VALUES (350,'Clinical Psychology',348);
INSERT INTO `branches` VALUES (351,'Cognition and Perception',348);
INSERT INTO `branches` VALUES (352,'Cognitive Psychology',348);
INSERT INTO `branches` VALUES (353,'Community Psychology',348);
INSERT INTO `branches` VALUES (354,'Developmental Psychology',348);
INSERT INTO `branches` VALUES (355,'Health Psychology',348);
INSERT INTO `branches` VALUES (356,'Industrial and Organizational Psychology',348);
INSERT INTO `branches` VALUES (357,'Personality and Social Contexts',348);
INSERT INTO `branches` VALUES (358,'Social Psychology',348);
INSERT INTO `branches` VALUES (359,'Sociology',287);
INSERT INTO `branches` VALUES (360,'Demography, Population, and Ecology',359);
INSERT INTO `branches` VALUES (361,'Family, Life Course, and Society',359);
INSERT INTO `branches` VALUES (362,'Gender and Sexuality',359);
INSERT INTO `branches` VALUES (363,'Inequality and Stratification',359);
INSERT INTO `branches` VALUES (364,'Medicine and Health',359);
INSERT INTO `branches` VALUES (365,'Place and Environment',359);
INSERT INTO `branches` VALUES (366,'Politics and Social Change',359);
INSERT INTO `branches` VALUES (367,'Race and Ethnicity',359);
INSERT INTO `branches` VALUES (368,'Regional Sociology',359);
INSERT INTO `branches` VALUES (369,'Rural sociology',359);
INSERT INTO `branches` VALUES (370,'Social Control, Law, Crime, and Deviance',359);
INSERT INTO `branches` VALUES (371,'Social Psychology and Interaction',359);
INSERT INTO `branches` VALUES (372,'Sociology of Culture',359);
INSERT INTO `branches` VALUES (373,'Theory, Knowledge and Science',359);
INSERT INTO `branches` VALUES (374,'Work, Economy and Organizations',359);
INSERT INTO `branches` VALUES (375,'Criminology',359);
INSERT INTO `branches` VALUES (376,'Criminology and Criminal Justice',287);
INSERT INTO `branches` VALUES (377,'Urban Studies and Planning',287);
INSERT INTO `branches` VALUES (378,'Arts and Humanities',NULL);
INSERT INTO `branches` VALUES (379,'Classics',378);
INSERT INTO `branches` VALUES (380,'Ancient History',379);
INSERT INTO `branches` VALUES (381,'Ancient Philosophy',379);
INSERT INTO `branches` VALUES (382,'Byzantine and Modern Greek',379);
INSERT INTO `branches` VALUES (383,'Classical Archaeology and Art History',379);
INSERT INTO `branches` VALUES (384,'Classical Literature and Philology',379);
INSERT INTO `branches` VALUES (385,'Comparative Literature',378);
INSERT INTO `branches` VALUES (386,'Feminist, Gender and Sexuality Studies',378);
INSERT INTO `branches` VALUES (387,'Rhetoric and Composition',378);
INSERT INTO `branches` VALUES (388,'History',378);
INSERT INTO `branches` VALUES (389,'African History',388);
INSERT INTO `branches` VALUES (390,'Asian History',388);
INSERT INTO `branches` VALUES (391,'European History',388);
INSERT INTO `branches` VALUES (392,'Islamic World History',388);
INSERT INTO `branches` VALUES (393,'Latin American History',388);
INSERT INTO `branches` VALUES (394,'United States History',388);
INSERT INTO `branches` VALUES (395,'Cultural History',388);
INSERT INTO `branches` VALUES (396,'Diplomatic History',388);
INSERT INTO `branches` VALUES (397,'Gender History',388);
INSERT INTO `branches` VALUES (398,'History of Religion',388);
INSERT INTO `branches` VALUES (399,'History of Science, Technology and Medicine',388);
INSERT INTO `branches` VALUES (400,'Intellectual History',388);
INSERT INTO `branches` VALUES (401,'Legal History',388);
INSERT INTO `branches` VALUES (402,'Medieval History',388);
INSERT INTO `branches` VALUES (403,'Military History',388);
INSERT INTO `branches` VALUES (404,'Political History',388);
INSERT INTO `branches` VALUES (405,'Social History',388);
INSERT INTO `branches` VALUES (406,"Women\'s History",388);
INSERT INTO `branches` VALUES (407,'Music',378);
INSERT INTO `branches` VALUES (408,'Music Composition',407);
INSERT INTO `branches` VALUES (409,'Ethnomusicology',407);
INSERT INTO `branches` VALUES (410,'Musicology',407);
INSERT INTO `branches` VALUES (411,'Music Theory',407);
INSERT INTO `branches` VALUES (412,'Philosophy',378);
INSERT INTO `branches` VALUES (413,'Continental Philosophy',412);
INSERT INTO `branches` VALUES (414,'Epistemology',412);
INSERT INTO `branches` VALUES (415,'Esthetics',412);
INSERT INTO `branches` VALUES (416,'Ethics and Political Philosophy',412);
INSERT INTO `branches` VALUES (417,'Feminist Philosophy',412);
INSERT INTO `branches` VALUES (418,'History of Philosophy',412);
INSERT INTO `branches` VALUES (419,'Logic and foundations of mathematics',412);
INSERT INTO `branches` VALUES (420,'Metaphysics',412);
INSERT INTO `branches` VALUES (421,'Philosophy of Language',412);
INSERT INTO `branches` VALUES (422,'Philosophy of Mind',412);
INSERT INTO `branches` VALUES (423,'Philosophy of Science',412);
INSERT INTO `branches` VALUES (424,'Religion',378);
INSERT INTO `branches` VALUES (425,'Biblical Studies',424);
INSERT INTO `branches` VALUES (426,'Comparative Methodologies and Theories of Religion',424);
INSERT INTO `branches` VALUES (427,'Religious Ethics',424);
INSERT INTO `branches` VALUES (428,'History of Religions of Western Origin',424);
INSERT INTO `branches` VALUES (429,'History of Religions of Eastern Origins',424);
INSERT INTO `branches` VALUES (430,'Religious Thought/Theology/Philosophy of Religion',424);
INSERT INTO `branches` VALUES (431,'Theatre and Performance Studies',378);
INSERT INTO `branches` VALUES (432,'Theatre History',431);
INSERT INTO `branches` VALUES (433,'Dramatic Literature, Criticism and Theory',431);
INSERT INTO `branches` VALUES (434,'Performance Studies',431);
INSERT INTO `branches` VALUES (435,'Playwriting',431);
INSERT INTO `branches` VALUES (436,'Film Studies',431);